project_id = "qwethimbtaamlhbajmal"

[functions.parse-program-excel]
verify_jwt = true

[functions.import-exercises]
verify_jwt = true

[functions.import-exercises-csv]
verify_jwt = true

[functions.import-program-csv]
verify_jwt = true

[functions.replace-program]
verify_jwt = false

[functions.track-visit]
verify_jwt = false